name: NPM publish CD workflow

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checking tag name and tag version
      if: github.event.release.tag_name != github.event.release.name
      run: |
        echo "Tag name must be same as tag version"
        exit 1
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v3.1.0
      with:
        git-user-signingkey: true
        git-commit-gpgsign: true
        git-tag-gpgsign: true
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: git config --global user.name "ppiyush13"
    - run: git config --global user.email "ppiyush13@gmail.com"
    - run: npm run build
    - run: npm test
    - run: npm version -s ${{github.event.release.tag_name}}
    - run: npm publish
      env:
        BRANCH_NAME: ${{github.event.release.target_commitish}}
        TAG_NAME: ${{github.event.release.tag_name}}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}